image: node:latest

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'


stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish
  environment: production
